---
root: true
extends:
  - "airbnb-base"
  - "plugin:react/recommended"
  - "plugin:prettier/recommended"
  - "plugin:jest/recommended"
  - "plugin:jest/style"

env:
  browser: true

rules:
  import/prefer-default-export: "off"
  import/no-extraneous-dependencies: "off"

settings:
  react:
    version: "detect"
