// Architecture guardrails for Flock Workday, checked on bytecode by byterails
// (https://github.com/flock-community/byterails) whenever workday-application is compiled.
//
// Declarations are relative to the base package `community.flock.eco.workday`, configured on the
// byterails-maven-plugin in workday-application/pom.xml. Only workday-application is checked; the
// vendored workday-core and workday-user modules are not.
//
// The `hexagonal` default rule set (workday-application/pom.xml) declares `domain` and isolates it:
// a class in it may only reference the language baseline (kotlin, java.lang, java.util, java.time,
// java.math, java.text) and the domain itself, never Spring, JPA, workday-core or workday-user.
// The `kotlin` rule set allows the Kotlin and Java standard libraries everywhere. Anything this
// file does not mention is a violation: `./mvnw compile -Dbyterails.reportOnly=true` lists them
// without failing the build.
byterails {
    // Generated by Wirespec from workday-application/src/main/wirespec: the HTTP contract.
    pkg("api") {
        allow("community.flock.wirespec")
        allow("org.springframework")
    }

    // Everything else: Spring wiring, JPA entities, services, controllers and the adapters that
    // implement the domain's ports. Only the domain boundary is enforced for now.
    pkg("application") {
        allowAnything()
    }
}
