// Architecture guardrails for Flock Workday, checked on bytecode by byterails
// (https://github.com/flock-community/byterails) in the Maven `verify` phase.
//
// Declarations are relative to the base package `community.flock.eco.workday`, configured in the
// root pom.xml together with the functional slices of the application:
//
//   application.person       people, their addresses and the link to their user account
//   application.client       clients the people work for
//   application.project      projects that group assignments
//   application.assignment   a person assigned to a client (and project) for a period and rate
//   application.contract     internal, external, management and service contracts
//   application.workday      hours worked on an assignment, their sheets and export
//   application.leaveday     holidays, plus days and (un)paid leave, and the holiday calendar feed
//   application.sickday      sick leave
//   application.event        company events, event days, ratings and budget categories
//   application.expense      cost and travel expenses (on the ports of the domain module)
//   application.laptop       laptops handed out to people
//   application.aggregation  reports that combine every slice, and the monthly hour reminder
//   application.budget       what each person spent of their hack and training budget
//   application.todo         leave, sick and work days and expenses awaiting approval
//   application.user         users, groups, authorities and login state
//
// Every slice gets the structure of the `slice { }` block below. Anything this file does not
// mention is a violation: `./mvnw verify -Dbyterails.reportOnly=true` lists them without failing.
byterails {
    // The Kotlin and Java standard libraries come from the `kotlin` default rule set (pom.xml).
    allow("org.slf4j")

    // The framework-free domain module: value types, domain services and the ports they need.
    pkg("domain") {
        isolated()
        allow("kotlin")
        allow("java")
        allow("org.jetbrains.annotations")
    }

    // Generated by Wirespec from workday-application/src/main/wirespec: the HTTP contract.
    pkg("api") {
        allow("community.flock.wirespec")
        allow("com.fasterxml.jackson")
        allow("org.springframework")
    }

    // Entry point: boots Spring and imports the wiring.
    pkg("application") {
        flat()
        allowAnything()
    }

    // Wiring and cross-cutting infrastructure: Spring configuration, security, cloud stubs.
    pkg("application.config") {
        allowAnything()
    }

    // Liquibase custom changes. The changelogs name these classes, so they never move.
    pkg("application.migrations") {
        allow("liquibase")
    }

    // Development seed data (src/develop), only compiled into the application with -Pdevelop.
    pkg("application.mocks") {
        allowAnything()
    }

    // The shared kernel: what every slice may use. It knows no slice.
    pkg("application.common") {
        allow("domain")
        allow("community.flock.eco.workday.core")
        allow("jakarta.persistence")
        allow("org.springframework")
    }
    pkg("application.common.document") {
        allow("com.google.cloud")
    }
    pkg("application.common.google") {
        allow("com.google.api")
        allow("com.google.auth")
        allow("community.flock.eco.workday.user")
    }
    pkg("application.common.ical") {
        allow("biweekly")
    }
    pkg("application.common.mail") {
        allow("application.common.properties")
        allow("com.mailjet")
        allow("org.json")
    }
    pkg("application.common.web") {
        allow("api")
        allow("com.fasterxml.jackson.databind")
    }

    slice {
        // What a slice offers the other slices: its entities and its services.
        // Repositories and controllers stay private to their slice.
        exported("model")
        exported("service")

        // Rules of every slice root, inherited by the packages of the slice.
        allow("domain")
        allow("application.common")
        allow("community.flock.eco.workday.core")
        allow("community.flock.eco.workday.user")
        allow("org.springframework.data.domain")

        // JPA entities, enums, authorities and the entity-to-domain mappers of the slice.
        pkg("model") {
            allow("jakarta.persistence")
            allow("org.hibernate.annotations")
            allow("com.fasterxml.jackson.annotation")
        }

        // Spring Data repositories and adapters for the ports of the domain module.
        pkg("persistence") {
            allow("model")
            allow("jakarta.persistence")
            allow("org.springframework.data")
            allow("org.springframework.stereotype")
            allow("org.springframework.transaction")
            naming {
                endsWith("Repository")
                endsWith("RepositoryImpl")
                endsWith("Adapter")
                endsWith("MapperKt")
            }
        }

        // Use cases: services, the forms they take and the notifications they send.
        pkg("service") {
            allow("model")
            allow("persistence")
            allow("org.springframework.stereotype")
            allow("org.springframework.transaction")
            allow("jakarta.transaction")
            allow("org.springframework.beans.factory.annotation")
            allow("org.springframework.context.i18n")
            allow("org.springframework.data.util")
            allow("com.fasterxml.jackson")
            allow("org.json")
        }

        // HTTP adapters implementing the Wirespec handlers.
        pkg("web") {
            allow("model")
            allow("service")
            allow("api")
            allow("community.flock.wirespec.kotlin")
            allow("org.springframework.web")
            allow("org.springframework.http")
            allow("org.springframework.security")
            allow("org.springframework.stereotype")
            allow("org.springframework.beans.factory.annotation")
            allow("org.springframework.boot.web.server")
            allow("org.springframework.boot.autoconfigure.condition")
            naming {
                endsWith("Controller")
                endsWith("ControllerKt")
                endsWith("Mapper")
                endsWith("MapperKt")
                endsWith("Handler")
                endsWith("Response")
            }
        }
    }
}
