// Architecture guardrails for Flock Workday, checked on bytecode by byterails
// (https://github.com/flock-community/byterails) whenever workday-application is compiled.
//
// Declarations are relative to the base package `community.flock.eco.workday`, configured on the
// byterails-maven-plugin in workday-application/pom.xml. Only workday-application is checked; the
// vendored workday-core and workday-user modules are not.
//
// The `hexagonal` default rule set (workday-application/pom.xml) declares `domain` and isolates it:
// a class in it may only reference the language baseline (kotlin, java.lang, java.util, java.time,
// java.math, java.text) and the domain itself, never Spring, JPA, workday-core or workday-user.
// The `kotlin` rule set allows the Kotlin and Java standard libraries everywhere. Anything this
// file does not mention is a violation: `./mvnw compile -Dbyterails.reportOnly=true` lists them
// without failing the build.
byterails {
    // Generated by Wirespec from workday-application/src/main/wirespec: the HTTP contract.
    pkg("api") {
        allow("community.flock.wirespec")
        allow("org.springframework")
    }

    // Spring wiring, JPA entities, services, controllers and the adapters that implement the
    // domain's ports. Only the domain boundary is enforced for now.
    pkg("application") {
        allowAnything()
    }

    // The domain, one package per functional slice of the application. Each slice is isolated like
    // the domain itself, gets the language baseline, and names the slices it builds on; it cannot
    // reach any other slice. The graph has no cycles: `common` and `user` are leaves, `person` is
    // what most slices hang off, `todo` and `budget` are read models over the others.
    val baseline = listOf("kotlin", "org.jetbrains.annotations", "java.lang", "java.util", "java.time", "java.math", "java.text")
    fun slice(name: String, vararg uses: String) =
        pkg("domain.$name") {
            isolated()
            baseline.forEach { allow(it) }
            uses.forEach { allow("domain.$it") }
        }

    slice("common") // Period, Day, Hours, Hourly, Monthly, Approvable, ApprovalStatus, Document, Page, Event
    slice("user") // users, accounts and groups
    slice("person", "user") // people, their address and the user they log in as
    slice("client") // clients the people work for
    slice("project") // projects that group assignments
    slice("assignment", "common", "client", "person", "project") // a person at a client for a period and rate
    slice("contract", "common", "person") // internal, external, management and service contracts
    slice("workday", "common", "assignment") // hours worked on an assignment, with their sheets
    slice("leaveday", "common", "person") // holidays, plus days and (un)paid leave
    slice("sickday", "common", "person") // sick leave
    slice("event", "common", "person") // hack days, conferences and other events, with their attendees
    slice("expense", "common", "person") // cost and travel expenses, their services and ports
    slice("laptop", "person") // laptops handed out to people
    slice("budget", "event") // what a person spent of their hack and training budget
    slice("todo", "person", "assignment", "leaveday", "sickday", "workday", "expense") // registrations awaiting approval
}
