version: "3.9"
services:
#  workday:
#    image: gcr.io/flock-eco/flock-eco-workday-develop:snapshot
#    environment:
#      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/application_default_credentials.json
#    volumes:
#      - type: bind
#        source: $HOME/.config/gcloud/application_default_credentials.json
#        target: /tmp/keys/application_default_credentials.json
#        read_only: true
#    ports:
#      - "8080:8080"
#    networks:
#      - intranet

  oathkeeper:
    image: oryd/oathkeeper:v0.40.2
    depends_on:
      - kratos
      - kratos-selfservice-ui-node
      - kratos-setup-users
#      - workday
    ports:
      - "8081:4455"
      - "4456:4456"
    command: serve proxy -c "/etc/config/oathkeeper/config.yaml"
    environment:
      - LOG_LEVEL=debug
      - ERRORS_HANDLERS_REDIRECT_CONFIG_TO=http://accounts.flock.local:8081/ui/login
      - MUTATORS_ID_TOKEN_CONFIG_ISSUER_URL=http://accounts.flock.local:8081
      - SERVE_PROXY_CORS_ALLOWED_ORIGINS_0=http://workday.flock.local:8081
      - SERVE_PROXY_CORS_ALLOWED_ORIGINS_1=http://accounts.flock.local:8081
      - SERVE_PROXY_CORS_ALLOWED_ORIGINS_2=http://fe-workday.flock.local:8081
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./docker/oathkeeper:/etc/config/oathkeeper

  #############
  ## Kratos  ##
  #############
  kratos:
    image: oryd/kratos:v0.13.0
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      #
      - SERVE_PUBLIC_BASE_URL=http://accounts.flock.local:8081/api
      - SERVE_ADMIN_BASE_URL=http://kratos:4434
      - SELFSERVICE_DEFAULT_BROWSER_RETURN_URL=http://workday.flock.local:8081
      - SELFSERVICE_ALLOWED_RETURN_URLS_0=http://accounts.flock.local:8081
      - SELFSERVICE_ALLOWED_RETURN_URLS_1=http://workday.flock.local:8081
      - SELFSERVICE_ALLOWED_RETURN_URLS_2=http://fe-workday.flock.local:8081
      # - BASE_PATH=/kratos
      - SELFSERVICE_FLOWS_ERROR_UI_URL=http://accounts.flock.local:8081/ui/error
      - SELFSERVICE_FLOWS_SETTINGS_UI_URL=http://accounts.flock.local:8081/ui/settings
      - SELFSERVICE_FLOWS_RECOVERY_UI_URL=http://accounts.flock.local:8081/ui/recovery
      - SELFSERVICE_FLOWS_VERIFICATION_UI_URL=http://accounts.flock.local:8081/ui/verification
      - SELFSERVICE_FLOWS_LOGOUT_UI_URL=http://accounts.flock.local:8081/ui/logout
      - SELFSERVICE_FLOWS_LOGOUT_AFTER_DEFAULT_BROWSER_RETURN_URL=http://workday.flock.local:8081
      - SELFSERVICE_FLOWS_LOGIN_UI_URL=http://accounts.flock.local:8081/ui/login
      - SELFSERVICE_FLOWS_REGISTRATION_UI_URL=http://accounts.flock.local:8081/ui/registration
    ports:
      - '4433:4433'
      - '4434:4434'
    depends_on:
      - kratos-migrate
    volumes:
      - type: bind
        source: ./docker/kratos
        target: /etc/config/kratos
    networks:
      - intranet
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  postgres-kratos:
    image: postgres:13.6
    environment:
      - POSTGRES_USER=kratos
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=kratos
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v0.13.0
    links:
      - postgres-kratos:postgres-kratos
    environment:
      - DSN=postgres://kratos:secret@postgres-kratos:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./docker/kratos
        target: /etc/config/kratos
    command: migrate sql -e --yes -c /etc/config/kratos/kratos.yml

  kratos-setup-users:
    image: atlassian/default-image:4 # TODO let's go leaner
    depends_on:
      - kratos
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./docker/kratos/identities
        target: /tmp
    command: /tmp/import_identities.sh

  #############################
  ## Kratos selfservice ui   ##
  #############################
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node@sha256:bcc49d047038e5f2c42a5f0b57948e303725df0221009853b1183bc54fc606c8 # TODO FIXME bump me
    environment:
      - KRATOS_PUBLIC_URL=http://kratos:4433
      - KRATOS_BROWSER_URL=http://accounts.flock.local:8081/api
      - BASE_PATH=/ui
    networks:
      - intranet
    ports:
      - "3002:3000"
    restart: on-failure

  ############
  ## Keto  ##
  ############
  keto:
    image: oryd/keto:v0.11.1-alpha.0
    networks:
      - intranet
    links:
      - postgres-keto:postgres-keto
    ports:
      - "4466:4466"
      - "4467:4467"
    environment:
      - DSN=postgres://keto:secret@postgres-keto:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4
    depends_on:
      - keto-migrate
    restart: on-failure
    volumes:
      - type: bind
        source: ./docker/keto
        target: /home/ory
  postgres-keto:
    image: postgres:13.6
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=keto
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=keto
    networks:
      - intranet

  keto-migrate:
    image: oryd/keto:v0.11.1-alpha.0
    links:
      - postgres-keto:postgres-keto
    volumes:
      - type: bind
        source: ./docker/keto
        target: /home/ory
    environment:
      - LOG_LEVEL=debug
      - DSN=postgres://keto:secret@postgres-keto:5432/keto?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    command: ["migrate", "up", "-y"]
    restart: on-failure

  keto-add-access-rules:
    image: oryd/keto:v0.11.1-alpha.0
    networks:
      - intranet
    environment:
      - LOG_LEVEL=debug
      - KETO_WRITE_REMOTE=keto:4467
    entrypoint: /bin/sh /home/ory/update-zanzibar-rules.sh
    depends_on:
      - keto
    volumes:
      - type: bind
        source: ./docker/keto
        target: /home/ory
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

networks:
  intranet:
