version: v0.13.0

dsn: memory

serve:
  public:
    base_url: "--set-me-through-env-variable"
    cors:
      enabled: true
  admin:
    base_url: "--set-me-through-env-variable"


selfservice:
  default_browser_return_url: i-will-be-replaced
  allowed_return_urls:
    - "--set-me-through-env-variable--"

  methods:
    password:
      enabled: true
    oidc:
      enabled: false
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: /kratos-selfservice/error

    settings:
      ui_url: /kratos-selfservice/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: /kratos-selfservice/recovery
      use: code

    verification:
      enabled: true
      ui_url: /kratos-selfservice/verification
      use: code

    logout:
      after:
        default_browser_return_url: /kratos-selfservice/login

    login:
      ui_url: /kratos-selfservice/login
      lifespan: 10m
      after:
        hooks:
          - hook: require_verified_address

    registration:
      lifespan: 10m
      ui_url: /kratos-selfservice/registration
      after:
        password:
          hooks:
            - hook: session

session:
  cookie:
    domain: flock.local
    name: flock_community_session
  lifespan: 1h
  earliest_possible_extend: 10m
  whoami:
    required_aal: aal1

log:
  level: debug
  format: text
  leak_sensitive_values: true

# Settings for both anti-CSRF and session cookies
cookies:
  domain: flock.local

# Secrets are purposefully set to 'unsafe' values. Do not use in production
secrets:
  default:
    - SOME-DEFAULT-SECRET
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
