- id: oathkeeper-jwks
  version: v0.40.2
  upstream:
    url: http://oathkeeper:4456
  match:
    url: http://accounts.flock.local:8081/.well-known/jwks.json
    methods:
      - GET
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: redirect

- id: kratos-public-api
  version: v0.40.2
  upstream:
    url: http://kratos:4433
    strip_path: /api
  match:
    url: http://accounts.flock.local:8081/api/<.*>
    methods:
      - GET
      - POST
      - PUT
      - PATCH
      - OPTIONS
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: redirect

- id: kratos-admin-api
  version: v0.40.2
  upstream:
    url: http://kratos:4434
  match:
    url: http://accounts.flock.local:8081/admin/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: noop # protect me
  authorizer:
    handler: allow # protect me
  mutators:
    - handler: noop
  errors:
    - handler: redirect

- id: kratos-self-service-ui
  version: v0.40.2
  upstream:
    url: http://kratos-selfservice-ui-node:3000
  match:
    url: http://accounts.flock.local:8081/ui/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: redirect

- id: rootpath-to-ui
  version: v0.40.2
  upstream:
    url: http://kratos-selfservice-ui-node:3000/ui/
  match:
    url: http://accounts.flock.local:8081/<(ui)?>
    methods:
      - GET
  authenticators:
    - handler: unauthorized
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: redirect
      config:
        to: http://accounts.flock.local:8081/ui/
        return_to_query_param: ""
        code: 301
