- id: workday-everything
  upstream:
    url: https://workday-app-x6nsuevzyq-ew.a.run.app
  version: v0.40.3
  match:
    url: https://workday.flock.community/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: json

- id: shadow-workday-everything
  upstream:
    url: https://workday-app-ory-x6nsuevzyq-ew.a.run.app
  version: v0.40.3
  match:
    url: https://ory.workday.flock.community/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: noop
  authorizer:
    handler: allow
  mutators:
    - handler: noop
  errors:
    - handler: json
