import { makeStyles } from "@material-ui/core/styles";

export const useStyles = makeStyles((theme) => ({
  dialogContent: {
    margin: "auto",
    maxWidth: 900,
  },
  exportSnackBar: {
    display: "flex",
    justifyItems: "center",
    alignItems: "center",
    padding: "1rem",
    border: "2px solid",
    borderColor: theme.palette.success["600"],
    borderRadius: "5px",
    backgroundColor: theme.palette.success["200"],
  },
  exportMessage: {
    marginRight: "0.5rem",
  },
  calendarContainer: {
    width: "100%",
    marginTop: theme.spacing(2),
  },
  calendarHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: theme.spacing(2),
  },
  yearSelector: {
    minWidth: 100,
    marginLeft: theme.spacing(2),
  },
  currentMonthButton: {
    marginRight: theme.spacing(1),
    textTransform: 'none',
  },
  weekRow: {
    display: "flex",
    width: "100%",
  },
  weekNumberCell: {
    width: "70px",
    padding: theme.spacing(1),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.palette.grey[100],
    borderBottom: `1px solid ${theme.palette.grey[300]}`,
    fontWeight: "bold",
  },
  dayHeader: {
    flex: 1,
    padding: theme.spacing(1),
    textAlign: "center",
    borderBottom: `1px solid ${theme.palette.grey[300]}`,
  },
  dayCell: {
    flex: 1,
    position: "relative",
    height: "80px",
    backgroundColor: theme.palette.grey[100],
    border: `1px solid ${theme.palette.grey[300]}`,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    "&:hover": {
      backgroundColor: theme.palette.grey[200],
    },
  },
  dayCellSelected: {
    border: `2px solid ${theme.palette.primary.main}`,
  },
  dayNumber: {
    position: "absolute",
    top: "2px",
    left: "5px",
    fontSize: "0.75rem",
    color: theme.palette.text.secondary,
  },
  hoursDisplay: {
    fontSize: "1.5rem",
    fontWeight: "bold",
  },
  hoursInput: {
    width: "40px",
    margin: 0,
    padding: 0,
    "& input": {
      textAlign: 'center',
      padding: '0px',
    }
  },
  totalCell: {
    flex: 1,
    padding: theme.spacing(1),
    textAlign: "center",
    backgroundColor: theme.palette.grey[100],
    borderBottom: `1px solid ${theme.palette.grey[300]}`,
    fontWeight: "bold",
  },
  // Event indicator - bottom right
  eventIndicator: {
    position: "absolute",
    bottom: "2px",
    right: "2px",
    width: "20px",
    height: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "4px",
    fontSize: "0.7rem",
    color: "black",
    fontWeight: "bold",
  },
  // Vacation indicator - bottom left
  vacationIndicator: {
    position: "absolute",
    bottom: "2px",
    left: "2px",
    width: "20px",
    height: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "4px",
    fontSize: "0.7rem",
    color: "white",
    fontWeight: "bold",
  },
  // Sick indicator - top right
  sickIndicator: {
    position: "absolute",
    top: "2px",
    right: "2px",
    width: "20px",
    height: "20px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: "4px",
    fontSize: "0.7rem",
    color: "white",
    fontWeight: "bold",
  },
  summaryRow: {
    display: "flex",
    alignItems: "center",
    marginTop: theme.spacing(1),
    marginBottom: theme.spacing(1),
  },
  summaryItem: {
    display: "flex",
    alignItems: "center",
    marginRight: theme.spacing(2),
    padding: theme.spacing(1),
    borderRadius: '4px',
  },
  summaryColor: {
    width: "20px",
    height: "20px",
    marginRight: theme.spacing(1),
    borderRadius: "4px",
  },
  summaryText: {
    fontWeight: "bold",
    marginRight: theme.spacing(1),
  },
  summaryHours: {
    minWidth: "20px",
    height: "20px",
    padding: '0 4px',
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderRadius: "4px",
    fontWeight: "bold",
  },
  monthTotal: {
    marginTop: theme.spacing(1),
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: theme.palette.grey[800],
    color: "white",
    padding: theme.spacing(1),
  },
  monthTotalLabel: {
    marginRight: theme.spacing(2),
  },
  monthTotalValue: {
    fontSize: "1.5rem",
    fontWeight: "bold",
  },
  quickFillButtons: {
    display: "flex",
    marginBottom: theme.spacing(1),
  },
  fillWithButtons: {
    display: "flex",
    alignItems: "center",
    margin: '16px 0',
  },
  fillButton: {
    minWidth: '40px',
    margin: '0 4px',
  },
  navButtons: {
    display: "flex",
    alignItems: "center",
  },
}));
