- id: workday-everything
  upstream:
#    url: http://workday:8080
    # to allow to use 'local' app rather than docker one
    url: http://host.docker.internal:8080
  version: v0.40.2
  match:
    url: http://workday.flock.local:8081/<.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
  authenticators:
    - handler: cookie_session
  authorizer:
    handler: allow
  mutators:
    - handler: header
    - handler: id_token
      config:
        claims: |
          {
            "aud": ["http://workday.flock.local:8081"],
            "email": "{{ print .Extra.identity.traits.email }}"
          }
  errors:
    - handler: redirect
