version: v0.11.1-alpha.0

log:
  level: debug

namespaces:
  location: file:///home/ory/namespaces/


serve:
  read:
    host: 0.0.0.0
    port: 4466
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie

  write:
    host: 0.0.0.0
    port: 4467
    cors:
      enabled: true
      allowed_origins:
        - "*"
      allowed_headers:
        - Authorization
        - Cookie
        - Content-Type
      exposed_headers:
        - Content-Type
        - Set-Cookie

dsn: memory
